### ISSUE TITLE
npm run dev 出错

### ISSUE THREAD

**Issue by fujunfei** [goldvideo/h265player#27]
请问下最新的node版本install，会不会有问题，我用的windows环境node12.18.3的版本，intall没有报错，但是npm run dev后出现下面的情况：
 Error: No files matching the pattern "D:\work\h265player-master\src\themes\**\*.css" were found.
    at D:\work\h265player-master\node_modules\stylelint\lib\standalone.js:214:12
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
不知道什么原因造成的，好像还是少了什么依赖

**Comment by jarry** [comment]
Error: No files matching the pattern "D:\work\h265player-master\src\themes***.css" were found. 
看下这个文件在吗

**Comment by ryngrok** [comment]
你好，大佬。我也有这样子的报错，说是没有找到themes\**\*.css文件，但是我去翻了这个文件夹，有这个文件夹，并且里面也有css文件的

**Comment by snxly** [comment]
"stylelint": "^13.5.0",
"stylelint-webpack-plugin": "^0.10.5",
看一下这两个包的版本，分别安装13.5.0 和 0.10.5版本试试

**Comment by iisfish123** [comment]
我也有这样的问题，请问下怎么解决？

**Comment by huafeis** [comment]
有谁解决了这个问题的？

**Comment by Tobee4Lin** [comment]
Error: No files matching the pattern "C:\Users\phantomtiger\Desktop\HEVC-video-demo\h265player-master\src\themes\**\*.css" were found.
此报错直接去node_modules中找到\stylelint\lib\standalone.js:207行，将相关路径判空代码先注释。然后运行npm run dev进行打包，然后dist文件夹就会生成goldplay-h265.css和goldplay-h265-sdk.js两个文件。接着在文件根目录下使用http-server跑一个服务器，或用其他工具跑起本地服务也行。点开demo.html即可看到页面

![image](https://user-images.githubusercontent.com/30073154/119757791-0faad780-bed8-11eb-984d-cfc37676e96b.png)

**Comment by abcdxiangpan** [comment]
npm run dev卡住不动了是怎么回事

**Comment by yiwen03** [comment]
run dev 是一个开发模式 ，执行的webpack watch命令，如果修改代码，会自动 进行编译的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "goldvideo/h265player"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月18日(星期一) 晚上6:27
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [goldvideo/h265player] npm run dev 出错 (#27)





 
npm run dev卡住不动了是怎么回事
