### ISSUE TITLE
你好，运行时出错，提示Error: No files matching the pattern "E:\goldvideo\h265player\src\themes\**\*.css" were found.     at E:\goldvideo\h265player\node_modules\stylelint\lib\standalone.js:212:12     at processTicksAndRejections (internal/process/task_queues.js:93:5)

### ISSUE THREAD

**Issue by xhlichen163** [goldvideo/h265player#41]
![image](https://user-images.githubusercontent.com/28588284/103500174-8beb4280-4e85-11eb-9080-02e270913e68.png)
Error: No files matching the pattern "E:\goldvideo\h265player\src\themes\**\*.css" were found.
    at E:\goldvideo\h265player\node_modules\stylelint\lib\standalone.js:212:12
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by snxly** [comment]
npm i stylelint@13.5.0
npm i stylelint-webpack-plugin@0.10.5

**Comment by hlgf** [comment]
还是跑不起来

**Comment by 12138tang** [comment]
我也遇到这个问题，请问楼主解决了吗

**Comment by baomihuayu** [comment]
[http://ossexam.comnet.top/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20210528230051.png](url)
在build文件夹里webpack.base.conf.js文件里注释掉图片里红框的css插件
